include_guard(GLOBAL)

# Generated by cpkg sync.
# Include this file from the root CMakeLists.txt of your STM32CubeMX project.
# Use wtr_link_packages(<target>) for plain target_link_libraries(...).
# Use wtr_link_packages_public(<target>) to link with PUBLIC scope.

set(WTR_MANAGED_REPOSITORIES
    BasicComponents
    ChassisController
    MotorDrivers
    VelocityProfile
)

set(WTR_MANAGED_PACKAGE_DIRS
    Modules/BasicComponents/utils
    Modules/BasicComponents/libs/control/mit_pd
    Modules/MotorDrivers/core
    Modules/BasicComponents/libs/control/pid_motor
    Modules/MotorDrivers/controllers
    Modules/ChassisController/Core
    Modules/VelocityProfile/Core
    Modules/VelocityProfile/SCurve
    Modules/ChassisController/Controller/Master
    Modules/BasicComponents/bsp/gpio_driver
    Modules/ChassisController/Chassis/Steering4
    Modules/ChassisController/Localization/JustEncoder
    Modules/BasicComponents/libs/utils/ring_buffer
    Modules/BasicComponents/bsp/can_driver
    Modules/BasicComponents/services/watchdog
    Modules/MotorDrivers/motors/DJI
    Modules/BasicComponents/libs/utils/fixed_map
    Modules/MotorDrivers/motors/VESC
)

foreach(_wtr_package_dir IN LISTS WTR_MANAGED_PACKAGE_DIRS)
    if(NOT EXISTS "${CMAKE_CURRENT_LIST_DIR}/../${_wtr_package_dir}/CMakeLists.txt")
        message(FATAL_ERROR "Missing managed package '${CMAKE_CURRENT_LIST_DIR}/../${_wtr_package_dir}'. Run cpkg sync.")
    endif()

    add_subdirectory(
        "${CMAKE_CURRENT_LIST_DIR}/../${_wtr_package_dir}"
        "${CMAKE_BINARY_DIR}/cpkg/${_wtr_package_dir}"
    )
endforeach()

set(WTR_DIRECT_PACKAGE_TARGETS
    utils
    Chassis::ControllerMaster
    Chassis::Core
    Chassis::Steering4
    ChassisLocalization::JustEncoder
    MotorDrivers::Controller
    MotorDrivers::DJI
    MotorDrivers::VESC
)

set(WTR_RESOLVED_PACKAGE_TARGETS
    utils
    libs::MIT_PD
    MotorDrivers::Core
    libs::PIDMotor
    MotorDrivers::Controller
    Chassis::Core
    VelocityProfile::Core
    VelocityProfile::SCurve
    Chassis::ControllerMaster
    bsp::GPIO_Driver
    Chassis::Steering4
    ChassisLocalization::JustEncoder
    libs::RingBuffer
    bsp::CANDriver
    services::Watchdog
    MotorDrivers::DJI
    libs::FixedMap
    MotorDrivers::VESC
    stm32cubemx
    FreeRTOS
)

add_library(wtr_project_dependencies INTERFACE)
target_link_libraries(wtr_project_dependencies INTERFACE ${WTR_DIRECT_PACKAGE_TARGETS})

function(wtr_link_packages target)
    target_link_libraries(${target} ${WTR_DIRECT_PACKAGE_TARGETS})
endfunction()

function(wtr_link_packages_public target)
    target_link_libraries(${target} PUBLIC ${WTR_DIRECT_PACKAGE_TARGETS})
endfunction()
